#!/bin/bash
#
# Update the NordVPN WireGuard (NordLynx) server list for the VPN Client Gateway.
#
# This replaces the old OpenVPN-era updater (which relied on NordVPN API
# endpoints and Python 2 libraries that no longer exist). It queries the
# current NordVPN public API for every server that supports WireGuard and
# writes a vpnservers.xml that embeds, for each server, the data the gateway
# needs to switch to it without any further network calls:
#
#   <servername>  hostname (e.g. us11894.nordvpn.com)
#   <countryname> country, used for grouping/labels
#   <regionname>  city
#   <pubkey>      the server's WireGuard public key
#   <endpoint>    ip:51820
#   <flagfile>    ISO country-code flag (e.g. US.svg)
#
# Requirements: bash, curl, jq.  (No Python, no provider account needed - the
# server catalogue is public.)
#
# Usage:
#   ./vpn_update.sh [output.xml]
#
# Environment overrides:
#   MAX_PER_COUNTRY   max servers listed per country in the full list (default 4)
#   BASIC_CODES       space-separated ISO codes for the "basic" flag grid
#   VPNMGMT_DIR       if set, the generated file is also copied here as
#                     vpnservers.xml (e.g. /var/www/vpnmgmt)
#
set -euo pipefail

API="https://api.nordvpn.com/v1/servers?filters[servers_technologies][identifier]=wireguard_udp&limit=8000"
WG_PORT="51820"
MAX_PER_COUNTRY="${MAX_PER_COUNTRY:-4}"
BASIC_CODES="${BASIC_CODES:-US GB CA DE NL FR SE CH AU JP SG ES IT NO}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${1:-$SCRIPT_DIR/vpnservers.xml}"

# --- dependency check -------------------------------------------------------
need() { command -v "$1" >/dev/null 2>&1; }

install_deps() {
	local missing=()
	need curl || missing+=("curl")
	need jq || missing+=("jq")
	[ ${#missing[@]} -eq 0 ] && return 0
	echo ":: Installing dependencies: ${missing[*]}"
	if need apt-get; then
		sudo apt-get update -qq && sudo apt-get install -y "${missing[@]}"
	elif need apk; then
		sudo apk add --no-cache "${missing[@]}"
	elif need dnf; then
		sudo dnf install -y "${missing[@]}"
	elif need pacman; then
		sudo pacman -Sy --noconfirm "${missing[@]}"
	else
		echo "!! Please install: ${missing[*]}" >&2
		exit 1
	fi
}

install_deps

# --- fetch ------------------------------------------------------------------
TMPJSON="$(mktemp)"
trap 'rm -f "$TMPJSON"' EXIT

echo ":: Fetching NordVPN WireGuard server catalogue ..."
curl -fsS -g --max-time 120 "$API" -o "$TMPJSON"

count="$(jq 'length' "$TMPJSON")"
if [ "$count" -lt 1 ]; then
	echo "!! No servers returned from the NordVPN API." >&2
	exit 1
fi
echo ":: Retrieved $count WireGuard servers."

# --- build the "basic" flag grid (lowest load per popular country) ----------
basic_json="$(printf '%s\n' "$BASIC_CODES" | jq -R 'split(" ")')"

basic_xml="$(jq -r --argjson basic "$basic_json" '
	([ .[] | {host: .hostname, load: .load,
	          code: (.locations[0].country.code | ascii_upcase
	                 | if . == "UK" then "GB" else . end)} ]) as $list
	| $basic[]
	| . as $c
	| ($list | map(select(.code == $c)) | sort_by(.load) | .[0]) as $s
	| select($s != null)
	| "\t\t<servername>\($s.host)</servername>"
' "$TMPJSON")"

# --- build the full list (grouped by country, capped per country) -----------
full_xml="$(jq -r --argjson maxper "$MAX_PER_COUNTRY" '
	def esc: gsub("&"; "&amp;") | gsub("<"; "&lt;") | gsub(">"; "&gt;");
	[ .[] | {
		host:    .hostname,
		ip:      .station,
		load:    .load,
		country: (.locations[0].country.name),
		code:    (.locations[0].country.code | ascii_upcase
		          | if . == "UK" then "GB" else . end),
		city:    (.locations[0].country.city.name // ""),
		pub:     ([ .technologies[]? | select(.identifier == "wireguard_udp")
		            | .metadata[]? | select(.name == "public_key") | .value ] | .[0])
	} | select(.pub != null and .ip != null and .country != null) ]
	| group_by(.country)
	| sort_by(.[0].country)
	| .[]
	| sort_by(.load)[0:$maxper][]
	| "\t<vpnserver>\n"
	+ "\t\t<servername>\(.host)</servername>\n"
	+ "\t\t<countryname>\(.country | esc)</countryname>\n"
	+ "\t\t<regionname>\(.city | esc)</regionname>\n"
	+ "\t\t<pubkey>\(.pub)</pubkey>\n"
	+ "\t\t<endpoint>\(.ip):'"$WG_PORT"'</endpoint>\n"
	+ "\t\t<flagfile>\(.code).svg</flagfile>\n"
	+ "\t</vpnserver>"
' "$TMPJSON")"

# --- assemble the XML -------------------------------------------------------
TMPOUT="$(mktemp)"
{
	echo '<?xml version="1.0"?>'
	echo '<!-- Generated by vpn_update.sh (NordVPN / WireGuard). Re-run periodically to refresh server keys. -->'
	echo '<vpnserverinfo>'
	echo '<basicvpnservers>'
	echo "$basic_xml"
	echo '</basicvpnservers>'
	echo '<vpnservers>'
	echo "$full_xml"
	echo '</vpnservers>'
	echo '</vpnserverinfo>'
} > "$TMPOUT"

# Validate if xmllint is available.
if need xmllint; then
	xmllint --noout "$TMPOUT"
fi

mv "$TMPOUT" "$OUT"
servers_listed="$(grep -c '<vpnserver>' "$OUT" || true)"
echo ":: Wrote $servers_listed servers to $OUT"

# --- optionally deploy to the live web directory ----------------------------
if [ -n "${VPNMGMT_DIR:-}" ]; then
	if [ -d "$VPNMGMT_DIR" ]; then
		sudo cp "$OUT" "$VPNMGMT_DIR/vpnservers.xml"
		echo ":: Deployed to $VPNMGMT_DIR/vpnservers.xml"
	else
		echo "!! VPNMGMT_DIR ($VPNMGMT_DIR) does not exist; skipping deploy." >&2
	fi
fi

echo ":: Done."
