#!/bin/bash
#
# import-wireguard-config.sh
#
# Bring in a standard WireGuard config from ANY vendor (Mullvad, Proton, AirVPN,
# IVPN, a self-hosted peer, …) so the gateway can use it without vendor-specific
# code. It:
#   1. installs the config as /etc/wireguard/wg0.conf (adding a "# Server" marker)
#   2. selects the WireGuard backend and the "custom" provider
#   3. generates a one-entry server list (vpnservers.xml) for the web UI
#
#   sudo ./import-wireguard-config.sh /path/to/provider.conf [COUNTRY_CODE] [Country Name]
#
# e.g.  sudo ./import-wireguard-config.sh mullvad-se.conf SE Sweden
#
set -euo pipefail

[ "$(id -u)" -eq 0 ] || { echo "Please run as root (sudo $0)." >&2; exit 1; }

SRC="${1:-}"
CC="${2:-}"
CNAME="${3:-Custom}"
[ -n "$SRC" ] && [ -r "$SRC" ] || { echo "Usage: $0 <wireguard.conf> [COUNTRY_CODE] [Country Name]" >&2; exit 1; }

WG_CONF="/etc/wireguard/wg0.conf"
BACKEND_FILE="/etc/vpngw/backend"
PROVIDER_FILE="/etc/vpngw/provider"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

val() { grep -iE "^[[:space:]]*$1[[:space:]]*=" "$SRC" | head -n1 | sed -E 's/^[^=]*=[[:space:]]*//; s/[[:space:]]+$//'; }
ENDPOINT="$(val Endpoint)"
PUBKEY="$(val PublicKey)"
[ -n "$ENDPOINT" ] || { echo "No Endpoint found in $SRC." >&2; exit 1; }
HOST="${ENDPOINT%%:*}"

# 1. install the config with a "# Server" marker the UI can read.
install -d -m 700 /etc/wireguard
if grep -qiE '^[[:space:]]*#[[:space:]]*Server[[:space:]]*=' "$SRC"; then
	install -m 600 "$SRC" "$WG_CONF"
else
	awk -v host="$HOST" 'BEGIN{done=0} {print} /^\[Interface\]/ && !done {print "# Server = " host; done=1}' "$SRC" > "$WG_CONF"
	chmod 600 "$WG_CONF"
fi

# 2. select backend + provider.
install -d -m 755 /etc/vpngw
echo wireguard > "$BACKEND_FILE"
echo custom    > "$PROVIDER_FILE"

# 3. generate the server list for the web UI.
VPNMGMT_DIR="${VPNMGMT_DIR:-}"
if [ -z "$VPNMGMT_DIR" ]; then
	for d in /var/www/vpnmgmt /var/www/html/vpnmgmt /var/www/localhost/htdocs/vpnmgmt; do
		[ -d "$d" ] && { VPNMGMT_DIR="$d"; break; }
	done
fi
[ -n "$VPNMGMT_DIR" ] || VPNMGMT_DIR="$SCRIPT_DIR/../www/vpnmgmt"

FLAG=""
[ -n "$CC" ] && FLAG="$(printf '%s' "$CC" | tr '[:lower:]' '[:upper:]').svg"

XML="$VPNMGMT_DIR/vpnservers.xml"
{
	echo '<?xml version="1.0"?>'
	echo '<!-- Generated by import-wireguard-config.sh (custom WireGuard provider). -->'
	echo '<vpnserverinfo>'
	echo '<basicvpnservers>'
	echo "		<servername>$HOST</servername>"
	echo '</basicvpnservers>'
	echo '<vpnservers>'
	echo '	<vpnserver>'
	echo "		<servername>$HOST</servername>"
	echo "		<countryname>$CNAME</countryname>"
	echo "		<regionname></regionname>"
	[ -n "$PUBKEY" ] && echo "		<pubkey>$PUBKEY</pubkey>"
	echo "		<endpoint>$ENDPOINT</endpoint>"
	[ -n "$FLAG" ] && echo "		<flagfile>$FLAG</flagfile>"
	echo '	</vpnserver>'
	echo '</vpnservers>'
	echo '</vpnserverinfo>'
} > "$XML"

install -d -m 755 "$VPNMGMT_DIR/vpn_providers/custom"
cp "$XML" "$VPNMGMT_DIR/vpn_providers/custom/vpnservers.xml" 2>/dev/null || true

echo "Imported $SRC -> $WG_CONF (backend=wireguard, provider=custom)."
echo "Server list written to $XML."
echo "Next: cd fw && sudo ./fw-config   (if not already configured), then  sudo wg-quick up wg0"
